services:
  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
      - "4430:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./private/ssl:/etc/nginx/ssl
      - .:/app
    depends_on:
      - php
    networks:
      - app-network

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php
    volumes:
      - .:/app
      - ./vendor:/app/vendor
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydatabase
    depends_on:
      - mariadb
    networks:
      - app-network

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    profiles: [production, development, staging]

  # PHPStan Service
  phpstan:
    build:
      context: .
      dockerfile: Dockerfile.phpstan
    container_name: phpstan
    volumes:
      - .:/app
    entrypoint: ["phpstan"]
    command: ["analyse", "--level=9", "/app/src"]

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: